name: Build_and_test

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: zh5uo8/mosze:latest
   
    steps:
      - uses: actions/checkout@v2

      - name: CPPCheck Static Code Analysis
        run: make sca

      - name: Upload CPPCheck report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.txt

      - name: Make
        run: make build

      - name: generate output
        run: ./harc.sh 

      - name: I/O test 1
        run: diff scenario_1_output.txt output1.txt
      - name: I/O test 2
        run: diff scenario_2_output.txt output2.txt

      - name: Valgrind memory check
        run: make memtest

